<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ7JVnVT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ7JVnVT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ7JVnVT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ7JVnVT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ7JVnVT\App_KernelDevDebugContainer([
    'container.build_hash' => 'J7JVnVT',
    'container.build_id' => 'b39891bf',
    'container.build_time' => 1666342057,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ7JVnVT');
