<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0JpYqrz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0JpYqrz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0JpYqrz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0JpYqrz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0JpYqrz\App_KernelDevDebugContainer([
    'container.build_hash' => '0JpYqrz',
    'container.build_id' => '29033c04',
    'container.build_time' => 1666273999,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0JpYqrz');
