<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFXmNiSI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFXmNiSI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFXmNiSI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFXmNiSI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFXmNiSI\App_KernelDevDebugContainer([
    'container.build_hash' => 'FXmNiSI',
    'container.build_id' => 'c568e43a',
    'container.build_time' => 1666268712,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFXmNiSI');
